export const languages = {
    arabic: {
        titleAccessories: "الإكسسوارات",
        titleMen: "أزياء الرجال",
        titleKids: "أزياء الأطفال",
        titleWomen: "أزياء النساء",
        titleOther: "الأقسام الأخرى",
        titleLogin: "تسجيل الدخول / اشتراك",
        titleLogout: "تسجيل الخروج",
        women: "النساء",
        men: "الرجال",
        kids: "الأطفال",
        necklaces: "قلادات",
        rings: "خواتم",
        bracelets: "أساور",
        watches: "ساعات",
        pajamas: "البيجامات",
        dresses: "فساتين",
        EveningDresses: "فساتين سهرة",
        Lingerie: "ﻻنجري",
        AbayasAndQatafin: "عبايات و قطافين",
        makeup: "تجميل",
        packages: "الباكيجات",
        houseware: "الأدوات المنزلية",
        TurkishMade: "صناعة تركية",
        localMade: "صناعة محلية",
        allProducts: "جميع المنتجات"
    },
    english: {
        titleAccessories: "Accessories",
        titleMen: "Men's Fashion",
        titleKids: "Kids Fashion",
        titleWomen: "Women's Fashion",
        titleOther: "Other",
        titleLogin: "Login / Register",
        titleLogout: "Logout",
        women: "Women's",
        men: "Men",
        kids: "Kids",
        necklaces: "Necklaces",
        rings: "Rings",
        bracelets: "Bracelets",
        watches: "Watches",
        pajamas: "Pajamas",
        dresses: "Dresses",
        Lingerie: "Lingerie",
        makeup: "Makeup",
        packages: "Packages",
        houseware: "Houseware",
        AbayasAndQatafin: "Abayas & Qatafin",
        EveningDresses: "Evening Dresses",
        TurkishMade: "Turkish Made",
        localMade: "Local Made",
        allProducts: "All Products"
    }

}